stages:
  split:
    cmd: python src/data/split_data.py
    deps:
    - data/raw_data/raw.csv
    - src/data/split_data.py
    outs:
    - data/processed/X_train.csv
    - data/processed/X_test.csv
    - data/processed/y_train.csv
    - data/processed/y_test.csv
  normalisation:
    cmd: python src/data/normalize.py
    deps:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - src/data/normalize.py
    outs:
    - data/processed/X_test_scaled.csv
    - data/processed/X_train_scaled.csv
  gridsearch:
    cmd: python src/models/gridsearch.py
    deps:
    - data/processed/X_test_scaled.csv
    - data/processed/X_train_scaled.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
    - src/models/gridsearch.py
    outs:
    - models/best_params.pkl
  train:
    cmd: python src/models/train_model.py
    deps:
    - data/processed/X_test_scaled.csv
    - data/processed/X_train_scaled.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
    - models/best_params.pkl
    - src/models/train_model.py
    outs:
    - models/trained_model.pkl
  evaluation:
    cmd: python src/models/evaluate.py
    deps:
    - data/processed/X_test_scaled.csv
    - data/processed/y_test.csv
    - models/trained_model.pkl
    - src/models/evaluate.py
    outs:
    - data/processed/predictions.csv
    metrics:
    - metrics/metrics.json:
        cache: false
